CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "passwd_hash" varchar(255) NOT NULL,
  "avatar_url" varchar(255),
  "status" varchar(20) DEFAULT 'online',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "conversations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" smallint NOT NULL,
  "name" varchar(100),
  "avatar_url" varchar(255),
  "owner_id" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "sender_id" bigint NOT NULL,
  "msg_type" smallint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "conversation_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "role" smallint DEFAULT 3,
  "joined_at" timestamp DEFAULT (now()),
  "last_read_message_id" bigint DEFAULT 0,
  "last_active_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "conversations" ("owner_id");

CREATE INDEX ON "messages" ("conversation_id", "created_at");

CREATE INDEX ON "messages" ("conversation_id", "id");

CREATE INDEX ON "messages" ("sender_id", "created_at");

CREATE UNIQUE INDEX ON "conversation_members" ("conversation_id", "user_id");

CREATE INDEX ON "conversation_members" ("user_id");

COMMENT ON COLUMN "users"."status" IS 'online, offline, busy';

COMMENT ON COLUMN "conversations"."type" IS '1: private, 2: group';

COMMENT ON COLUMN "messages"."msg_type" IS '1:text, 2:image, 3:file, 4:voice';

COMMENT ON COLUMN "conversation_members"."role" IS '1:owner, 2:admin, 3:member. 私聊也默认为 3，避免 NULL';

COMMENT ON COLUMN "conversation_members"."last_read_message_id" IS '0 表示未读任何消息';

ALTER TABLE "conversations" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_members" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_members" ADD FOREIGN KEY ("last_read_message_id") REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;
