-- 创建好友关系表
CREATE TABLE "friendships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "friend_id" bigint NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),
  "blocked" boolean DEFAULT false,
  "remark" varchar(100),
  CONSTRAINT unique_friendship UNIQUE ("user_id", "friend_id")
);

-- 创建用户资料扩展表
CREATE TABLE "user_profiles" (
  "user_id" bigint PRIMARY KEY,
  "nickname" varchar(50),
  "signature" varchar(200),
  "gender" varchar(10),
  "birthday" date,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

-- 创建消息转发记录表
CREATE TABLE "message_forwards" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "original_message_id" bigint NOT NULL,
  "forwarded_by" bigint NOT NULL,
  "target_conversation_id" bigint NOT NULL,
  "forwarded_at" timestamptz DEFAULT (now())
);

-- 创建群公告表
CREATE TABLE "group_announcements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "publisher_id" bigint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

-- 添加索引
CREATE INDEX ON "friendships" ("user_id");
CREATE INDEX ON "friendships" ("friend_id");
CREATE INDEX ON "friendships" ("status");
CREATE UNIQUE INDEX ON "friendships" ("user_id", "friend_id");

CREATE INDEX ON "message_forwards" ("original_message_id");
CREATE INDEX ON "message_forwards" ("forwarded_by");
CREATE INDEX ON "message_forwards" ("target_conversation_id");

CREATE INDEX ON "group_announcements" ("conversation_id");
CREATE INDEX ON "group_announcements" ("publisher_id");

-- 添加外键约束
ALTER TABLE "friendships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "friendships" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "message_forwards" ADD FOREIGN KEY ("original_message_id") REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "message_forwards" ADD FOREIGN KEY ("forwarded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "message_forwards" ADD FOREIGN KEY ("target_conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_announcements" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "group_announcements" ADD FOREIGN KEY ("publisher_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- 添加注释
COMMENT ON COLUMN "friendships"."status" IS 'pending: 待处理，accepted: 已接受，rejected: 已拒绝';
COMMENT ON COLUMN "friendships"."remark" IS '好友备注名';
