// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    type,
    name,
    owner_id
) VALUES (
    $1, $2, $3
) RETURNING id, type, name, avatar_url, owner_id, created_at, updated_at
`

type CreateConversationParams struct {
	Type    int16
	Name    pgtype.Text
	OwnerID pgtype.Int8
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Type, arg.Name, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, type, name, avatar_url, owner_id, created_at, updated_at FROM conversations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, type, name, avatar_url, owner_id, created_at, updated_at FROM conversations
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetConversationForUpdate(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForUpdate, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMyConversations = `-- name: ListMyConversations :many
SELECT c.id, c.type, c.name, c.avatar_url, c.owner_id, c.created_at, c.updated_at 
FROM conversations c
JOIN conversation_members cm ON c.id = cm.conversation_id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC
`

func (q *Queries) ListMyConversations(ctx context.Context, userID int64) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listMyConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AvatarUrl,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
