// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateMembers = `-- name: BatchCreateMembers :many
INSERT INTO conversation_members (
    conversation_id,
    user_id,
    role,
    last_read_message_id
) VALUES (
    -- 使用 sqlc 的 slice 参数
    $1,                   -- conversation_id
    unnest($2::bigint[]), -- user_ids
    $3,                   -- roles
    $4                    -- last_read_message_id
) RETURNING id, conversation_id, user_id, role, joined_at, last_read_message_id, last_active_at
`

type BatchCreateMembersParams struct {
	ConversationID    int64
	Column2           []int64
	Role              int16
	LastReadMessageID pgtype.Int8
}

func (q *Queries) BatchCreateMembers(ctx context.Context, arg BatchCreateMembersParams) ([]ConversationMember, error) {
	rows, err := q.db.Query(ctx, batchCreateMembers,
		arg.ConversationID,
		arg.Column2,
		arg.Role,
		arg.LastReadMessageID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMember{}
	for rows.Next() {
		var i ConversationMember
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.LastReadMessageID,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkMemberExists = `-- name: CheckMemberExists :one
SELECT EXISTS (
    SELECT 1 FROM conversation_members
    WHERE conversation_id = $1 AND user_id = $2
) as is_member
`

type CheckMemberExistsParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) CheckMemberExists(ctx context.Context, arg CheckMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMemberExists, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const countConversationMembers = `-- name: CountConversationMembers :one
SELECT COUNT(*) 
FROM conversation_members 
WHERE conversation_id = $1
`

func (q *Queries) CountConversationMembers(ctx context.Context, conversationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationMembers, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadMessages = `-- name: CountUnreadMessages :one
SELECT COUNT(*) 
FROM messages 
WHERE conversation_id = $1 AND id > $2 AND sender_id != $3
LIMIT 100
`

type CountUnreadMessagesParams struct {
	ConversationID int64
	ID             int64
	SenderID       int64
}

func (q *Queries) CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadMessages, arg.ConversationID, arg.ID, arg.SenderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversationMember = `-- name: CreateConversationMember :one
INSERT INTO conversation_members (
    conversation_id,
    user_id,
    role,
    last_read_message_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, conversation_id, user_id, role, joined_at, last_read_message_id, last_active_at
`

type CreateConversationMemberParams struct {
	ConversationID    int64
	UserID            int64
	Role              int16
	LastReadMessageID pgtype.Int8
}

func (q *Queries) CreateConversationMember(ctx context.Context, arg CreateConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, createConversationMember,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.LastReadMessageID,
	)
	var i ConversationMember
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LastReadMessageID,
		&i.LastActiveAt,
	)
	return i, err
}

const getConversationMember = `-- name: GetConversationMember :one
SELECT id, conversation_id, user_id, role, joined_at, last_read_message_id, last_active_at FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2 LIMIT 1
`

type GetConversationMemberParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) GetConversationMember(ctx context.Context, arg GetConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, getConversationMember, arg.ConversationID, arg.UserID)
	var i ConversationMember
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LastReadMessageID,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserAllConversations = `-- name: GetUserAllConversations :many
SELECT conversation_id FROM conversation_members
WHERE user_id = $1
`

func (q *Queries) GetUserAllConversations(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserAllConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var conversation_id int64
		if err := rows.Scan(&conversation_id); err != nil {
			return nil, err
		}
		items = append(items, conversation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT id, conversation_id, user_id, role, joined_at, last_read_message_id, last_active_at FROM conversation_members
where conversation_id = $1
`

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID int64) ([]ConversationMember, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMember{}
	for rows.Next() {
		var i ConversationMember
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.LastReadMessageID,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE FROM conversation_members
WHERE conversation_id = $1 
  AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.Exec(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE conversation_members
SET role = $3
WHERE conversation_id = $1 
  AND user_id = $2
`

type UpdateMemberRoleParams struct {
	ConversationID int64
	UserID         int64
	Role           int16
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.ConversationID, arg.UserID, arg.Role)
	return err
}

const updateReadStatus = `-- name: UpdateReadStatus :exec
UPDATE conversation_members
SET last_read_message_id = $3, 
    last_active_at = NOW()
WHERE conversation_id = $1 
  AND user_id = $2
`

type UpdateReadStatusParams struct {
	ConversationID    int64
	UserID            int64
	LastReadMessageID pgtype.Int8
}

func (q *Queries) UpdateReadStatus(ctx context.Context, arg UpdateReadStatusParams) error {
	_, err := q.db.Exec(ctx, updateReadStatus, arg.ConversationID, arg.UserID, arg.LastReadMessageID)
	return err
}
