// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendship = `-- name: AcceptFriendship :exec
UPDATE friendships
SET status = 'accepted',
    updated_at = NOW()
WHERE user_id = $1 AND friend_id = $2
`

type AcceptFriendshipParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) AcceptFriendship(ctx context.Context, arg AcceptFriendshipParams) error {
	_, err := q.db.Exec(ctx, acceptFriendship, arg.UserID, arg.FriendID)
	return err
}

const blockFriend = `-- name: BlockFriend :exec
UPDATE friendships
SET blocked = true,
    updated_at = NOW()
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
`

type BlockFriendParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) BlockFriend(ctx context.Context, arg BlockFriendParams) error {
	_, err := q.db.Exec(ctx, blockFriend, arg.UserID, arg.FriendID)
	return err
}

const checkFriendshipExists = `-- name: CheckFriendshipExists :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE ((user_id = $1 AND friend_id = $2)
       OR (user_id = $2 AND friend_id = $1))
    AND status = 'accepted'
    AND blocked = false
) as is_friend
`

type CheckFriendshipExistsParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) CheckFriendshipExists(ctx context.Context, arg CheckFriendshipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFriendshipExists, arg.UserID, arg.FriendID)
	var is_friend bool
	err := row.Scan(&is_friend)
	return is_friend, err
}

const checkGroupMuted = `-- name: CheckGroupMuted :one
SELECT EXISTS (
    SELECT 1 FROM group_mutes
    WHERE conversation_id = $1 AND user_id = $2 AND muted_until > NOW()
) as is_muted
`

type CheckGroupMutedParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) CheckGroupMuted(ctx context.Context, arg CheckGroupMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkGroupMuted, arg.ConversationID, arg.UserID)
	var is_muted bool
	err := row.Scan(&is_muted)
	return is_muted, err
}

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (
    user_id,
    friend_id,
    status
) VALUES (
    $1, $2, 'pending'
) ON CONFLICT (user_id, friend_id) DO UPDATE SET
    status = 'pending',
    updated_at = NOW()
RETURNING id, user_id, friend_id, status, created_at, updated_at, blocked, remark
`

type CreateFriendshipParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Blocked,
		&i.Remark,
	)
	return i, err
}

const createGroupAnnouncement = `-- name: CreateGroupAnnouncement :one
INSERT INTO group_announcements (
    conversation_id,
    publisher_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, conversation_id, publisher_id, content, created_at, updated_at
`

type CreateGroupAnnouncementParams struct {
	ConversationID int64
	PublisherID    int64
	Content        string
}

func (q *Queries) CreateGroupAnnouncement(ctx context.Context, arg CreateGroupAnnouncementParams) (GroupAnnouncement, error) {
	row := q.db.QueryRow(ctx, createGroupAnnouncement, arg.ConversationID, arg.PublisherID, arg.Content)
	var i GroupAnnouncement
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.PublisherID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageForward = `-- name: CreateMessageForward :one
INSERT INTO message_forwards (
    original_message_id,
    forwarded_by,
    target_conversation_id
) VALUES (
    $1, $2, $3
) RETURNING id, original_message_id, forwarded_by, target_conversation_id, forwarded_at
`

type CreateMessageForwardParams struct {
	OriginalMessageID    int64
	ForwardedBy          int64
	TargetConversationID int64
}

func (q *Queries) CreateMessageForward(ctx context.Context, arg CreateMessageForwardParams) (MessageForward, error) {
	row := q.db.QueryRow(ctx, createMessageForward, arg.OriginalMessageID, arg.ForwardedBy, arg.TargetConversationID)
	var i MessageForward
	err := row.Scan(
		&i.ID,
		&i.OriginalMessageID,
		&i.ForwardedBy,
		&i.TargetConversationID,
		&i.ForwardedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
`

type DeleteFriendshipParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getFriendList = `-- name: GetFriendList :many
SELECT u.id, u.username, u.avatar_url, u.status, u.created_at, u.updated_at,
       f.remark, f.created_at as friend_since
FROM friendships f
JOIN users u ON f.friend_id = u.id
WHERE f.user_id = $1 AND f.status = 'accepted' AND f.blocked = false
ORDER BY u.username
LIMIT $2 OFFSET $3
`

type GetFriendListParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type GetFriendListRow struct {
	ID          int64
	Username    string
	AvatarUrl   pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Remark      pgtype.Text
	FriendSince pgtype.Timestamptz
}

func (q *Queries) GetFriendList(ctx context.Context, arg GetFriendListParams) ([]GetFriendListRow, error) {
	rows, err := q.db.Query(ctx, getFriendList, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendListRow{}
	for rows.Next() {
		var i GetFriendListRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Remark,
			&i.FriendSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendRequestList = `-- name: GetFriendRequestList :many
SELECT u.id, u.username, u.avatar_url, f.created_at
FROM friendships f
JOIN users u ON f.user_id = u.id
WHERE f.friend_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type GetFriendRequestListRow struct {
	ID        int64
	Username  string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetFriendRequestList(ctx context.Context, friendID int64) ([]GetFriendRequestListRow, error) {
	rows, err := q.db.Query(ctx, getFriendRequestList, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendRequestListRow{}
	for rows.Next() {
		var i GetFriendRequestListRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_id, status, created_at, updated_at, blocked, remark FROM friendships
WHERE user_id = $1 AND friend_id = $2
LIMIT 1
`

type GetFriendshipParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Blocked,
		&i.Remark,
	)
	return i, err
}

const getFriendshipBidirectional = `-- name: GetFriendshipBidirectional :one
SELECT id, user_id, friend_id, status, created_at, updated_at, blocked, remark FROM friendships
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
LIMIT 1
`

type GetFriendshipBidirectionalParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) GetFriendshipBidirectional(ctx context.Context, arg GetFriendshipBidirectionalParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipBidirectional, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Blocked,
		&i.Remark,
	)
	return i, err
}

const getGroupAnnouncement = `-- name: GetGroupAnnouncement :one
SELECT id, conversation_id, publisher_id, content, created_at, updated_at FROM group_announcements
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetGroupAnnouncement(ctx context.Context, conversationID int64) (GroupAnnouncement, error) {
	row := q.db.QueryRow(ctx, getGroupAnnouncement, conversationID)
	var i GroupAnnouncement
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.PublisherID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMuteInfo = `-- name: GetGroupMuteInfo :one
SELECT id, conversation_id, user_id, muted_until, created_at FROM group_mutes
WHERE conversation_id = $1 AND user_id = $2 AND muted_until > NOW()
LIMIT 1
`

type GetGroupMuteInfoParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) GetGroupMuteInfo(ctx context.Context, arg GetGroupMuteInfoParams) (GroupMute, error) {
	row := q.db.QueryRow(ctx, getGroupMuteInfo, arg.ConversationID, arg.UserID)
	var i GroupMute
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.MutedUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageForwards = `-- name: GetMessageForwards :many
SELECT mf.id, mf.original_message_id, mf.forwarded_by, mf.target_conversation_id, mf.forwarded_at, m.content, m.msg_type
FROM message_forwards mf
JOIN messages m ON mf.original_message_id = m.id
WHERE mf.forwarded_by = $1
ORDER BY mf.forwarded_at DESC
LIMIT $2 OFFSET $3
`

type GetMessageForwardsParams struct {
	ForwardedBy int64
	Limit       int32
	Offset      int32
}

type GetMessageForwardsRow struct {
	ID                   int64
	OriginalMessageID    int64
	ForwardedBy          int64
	TargetConversationID int64
	ForwardedAt          pgtype.Timestamptz
	Content              string
	MsgType              int16
}

func (q *Queries) GetMessageForwards(ctx context.Context, arg GetMessageForwardsParams) ([]GetMessageForwardsRow, error) {
	rows, err := q.db.Query(ctx, getMessageForwards, arg.ForwardedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessageForwardsRow{}
	for rows.Next() {
		var i GetMessageForwardsRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalMessageID,
			&i.ForwardedBy,
			&i.TargetConversationID,
			&i.ForwardedAt,
			&i.Content,
			&i.MsgType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrivateConversation = `-- name: GetPrivateConversation :one
SELECT c.id, c.type, c.name, c.avatar_url, c.owner_id, c.created_at, c.updated_at FROM conversations c
JOIN conversation_members cm1 ON c.id = cm1.conversation_id
JOIN conversation_members cm2 ON c.id = cm2.conversation_id
WHERE c.type = 1
  AND cm1.user_id = $1
  AND cm2.user_id = $2
LIMIT 1
`

type GetPrivateConversationParams struct {
	UserID   int64
	UserID_2 int64
}

func (q *Queries) GetPrivateConversation(ctx context.Context, arg GetPrivateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getPrivateConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetail = `-- name: GetUserDetail :one
SELECT u.id, u.username, u.avatar_url, u.status, u.created_at, u.updated_at,
       up.nickname, up.signature, up.gender, up.birthday
FROM users u
LEFT JOIN user_profiles up ON u.id = up.user_id
WHERE u.id = $1
`

type GetUserDetailRow struct {
	ID        int64
	Username  string
	AvatarUrl pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Nickname  pgtype.Text
	Signature pgtype.Text
	Gender    pgtype.Text
	Birthday  pgtype.Date
}

func (q *Queries) GetUserDetail(ctx context.Context, id int64) (GetUserDetailRow, error) {
	row := q.db.QueryRow(ctx, getUserDetail, id)
	var i GetUserDetailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nickname,
		&i.Signature,
		&i.Gender,
		&i.Birthday,
	)
	return i, err
}

const inviteGroupMember = `-- name: InviteGroupMember :one
INSERT INTO conversation_members (
    conversation_id,
    user_id,
    role,
    last_read_message_id
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (conversation_id, user_id) DO NOTHING
RETURNING id, conversation_id, user_id, role, joined_at, last_read_message_id, last_active_at
`

type InviteGroupMemberParams struct {
	ConversationID    int64
	UserID            int64
	Role              int16
	LastReadMessageID pgtype.Int8
}

func (q *Queries) InviteGroupMember(ctx context.Context, arg InviteGroupMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, inviteGroupMember,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.LastReadMessageID,
	)
	var i ConversationMember
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LastReadMessageID,
		&i.LastActiveAt,
	)
	return i, err
}

const kickGroupMember = `-- name: KickGroupMember :exec
DELETE FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type KickGroupMemberParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) KickGroupMember(ctx context.Context, arg KickGroupMemberParams) error {
	_, err := q.db.Exec(ctx, kickGroupMember, arg.ConversationID, arg.UserID)
	return err
}

const leaveGroup = `-- name: LeaveGroup :exec
DELETE FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type LeaveGroupParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.Exec(ctx, leaveGroup, arg.ConversationID, arg.UserID)
	return err
}

const muteGroupMember = `-- name: MuteGroupMember :one
INSERT INTO group_mutes (
    conversation_id,
    user_id,
    muted_until
) VALUES (
    $1, $2, $3
) ON CONFLICT (conversation_id, user_id) DO UPDATE SET
    muted_until = $3,
    created_at = NOW()
RETURNING id, conversation_id, user_id, muted_until, created_at
`

type MuteGroupMemberParams struct {
	ConversationID int64
	UserID         int64
	MutedUntil     pgtype.Timestamptz
}

func (q *Queries) MuteGroupMember(ctx context.Context, arg MuteGroupMemberParams) (GroupMute, error) {
	row := q.db.QueryRow(ctx, muteGroupMember, arg.ConversationID, arg.UserID, arg.MutedUntil)
	var i GroupMute
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.MutedUntil,
		&i.CreatedAt,
	)
	return i, err
}

const rejectFriendship = `-- name: RejectFriendship :exec
UPDATE friendships
SET status = 'rejected',
    updated_at = NOW()
WHERE user_id = $1 AND friend_id = $2
`

type RejectFriendshipParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) RejectFriendship(ctx context.Context, arg RejectFriendshipParams) error {
	_, err := q.db.Exec(ctx, rejectFriendship, arg.UserID, arg.FriendID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, avatar_url, status, created_at, updated_at 
FROM users
WHERE username ILIKE $1 
   OR EXISTS (
       SELECT 1 FROM user_profiles up 
       WHERE up.user_id = users.id 
       AND (up.nickname ILIKE $1 OR up.signature ILIKE $1)
   )
ORDER BY username
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Username string
	Limit    int32
	Offset   int32
}

type SearchUsersRow struct {
	ID        int64
	Username  string
	AvatarUrl pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersCount = `-- name: SearchUsersCount :one
SELECT COUNT(*) FROM users
WHERE username ILIKE $1 
   OR EXISTS (
       SELECT 1 FROM user_profiles up 
       WHERE up.user_id = users.id 
       AND (up.nickname ILIKE $1 OR up.signature ILIKE $1)
   )
`

func (q *Queries) SearchUsersCount(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, searchUsersCount, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const transferGroupOwner = `-- name: TransferGroupOwner :exec
UPDATE conversation_members
SET role = CASE 
    WHEN user_id = $2 THEN 3
    WHEN user_id = $3 THEN 1
    ELSE role
END,
updated_at = NOW()
WHERE conversation_id = $1 
AND user_id IN ($2, $3)
`

type TransferGroupOwnerParams struct {
	ConversationID int64
	UserID         int64
	UserID_2       int64
}

func (q *Queries) TransferGroupOwner(ctx context.Context, arg TransferGroupOwnerParams) error {
	_, err := q.db.Exec(ctx, transferGroupOwner, arg.ConversationID, arg.UserID, arg.UserID_2)
	return err
}

const unblockFriend = `-- name: UnblockFriend :exec
UPDATE friendships
SET blocked = false,
    updated_at = NOW()
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
`

type UnblockFriendParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) UnblockFriend(ctx context.Context, arg UnblockFriendParams) error {
	_, err := q.db.Exec(ctx, unblockFriend, arg.UserID, arg.FriendID)
	return err
}

const unmuteGroupMember = `-- name: UnmuteGroupMember :exec
DELETE FROM group_mutes
WHERE conversation_id = $1 AND user_id = $2
`

type UnmuteGroupMemberParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) UnmuteGroupMember(ctx context.Context, arg UnmuteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, unmuteGroupMember, arg.ConversationID, arg.UserID)
	return err
}

const updateFriendRemark = `-- name: UpdateFriendRemark :exec
UPDATE friendships
SET remark = $3,
    updated_at = NOW()
WHERE user_id = $1 AND friend_id = $2
`

type UpdateFriendRemarkParams struct {
	UserID   int64
	FriendID int64
	Remark   pgtype.Text
}

func (q *Queries) UpdateFriendRemark(ctx context.Context, arg UpdateFriendRemarkParams) error {
	_, err := q.db.Exec(ctx, updateFriendRemark, arg.UserID, arg.FriendID, arg.Remark)
	return err
}

const updateGroupAnnouncement = `-- name: UpdateGroupAnnouncement :one
UPDATE group_announcements
SET content = $3,
    updated_at = NOW()
WHERE conversation_id = $1 AND publisher_id = $2
RETURNING id, conversation_id, publisher_id, content, created_at, updated_at
`

type UpdateGroupAnnouncementParams struct {
	ConversationID int64
	PublisherID    int64
	Content        string
}

func (q *Queries) UpdateGroupAnnouncement(ctx context.Context, arg UpdateGroupAnnouncementParams) (GroupAnnouncement, error) {
	row := q.db.QueryRow(ctx, updateGroupAnnouncement, arg.ConversationID, arg.PublisherID, arg.Content)
	var i GroupAnnouncement
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.PublisherID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupInfo = `-- name: UpdateGroupInfo :one
UPDATE conversations
SET name = COALESCE($2, name),
    avatar_url = COALESCE($3, avatar_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, type, name, avatar_url, owner_id, created_at, updated_at
`

type UpdateGroupInfoParams struct {
	ID        int64
	Name      pgtype.Text
	AvatarUrl pgtype.Text
}

func (q *Queries) UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateGroupInfo, arg.ID, arg.Name, arg.AvatarUrl)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users
SET avatar_url = COALESCE($2, avatar_url),
    status = COALESCE($3, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, passwd_hash, avatar_url, status, created_at, updated_at
`

type UpdateUserInfoParams struct {
	ID        int64
	AvatarUrl pgtype.Text
	Status    string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInfo, arg.ID, arg.AvatarUrl, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswdHash,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
INSERT INTO user_profiles (
    user_id,
    nickname,
    signature,
    gender,
    birthday,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) ON CONFLICT (user_id) DO UPDATE SET
    nickname = EXCLUDED.nickname,
    signature = EXCLUDED.signature,
    gender = EXCLUDED.gender,
    birthday = EXCLUDED.birthday,
    updated_at = NOW()
RETURNING user_id, nickname, signature, gender, birthday, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserID    int64
	Nickname  pgtype.Text
	Signature pgtype.Text
	Gender    pgtype.Text
	Birthday  pgtype.Date
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.Nickname,
		arg.Signature,
		arg.Gender,
		arg.Birthday,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Nickname,
		&i.Signature,
		&i.Gender,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
