// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  conversation_id,
  sender_id,
  msg_type,
  content
) VALUES (
  $1, $2, $3, $4
) RETURNING id, conversation_id, sender_id, msg_type, content, created_at, is_deleted
`

type CreateMessageParams struct {
	ConversationID int64
	SenderID       int64
	MsgType        int16
	Content        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.MsgType,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.MsgType,
		&i.Content,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :one
UPDATE messages
SET is_deleted = true
WHERE id = $1
RETURNING id, conversation_id, sender_id, msg_type, content, created_at, is_deleted
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, deleteMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.MsgType,
		&i.Content,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, sender_id, msg_type, content, created_at, is_deleted FROM messages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.MsgType,
		&i.Content,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const listHistoryMessages = `-- name: ListHistoryMessages :many
SELECT 
    id,
    conversation_id,
    sender_id,
    msg_type,
    content,
    created_at,
    is_deleted
FROM messages
WHERE 
    conversation_id = $1 
    AND is_deleted = FALSE
    -- 关键逻辑：如果提供了 cursor_id，只查比它小的 ID
    -- sqlc.narg 允许参数为 NULL，实现可选过滤
    AND ($3::bigint IS NULL OR id < $3::bigint)
ORDER BY id DESC  -- 必须按 ID 倒序（或时间倒序），保证一致性
LIMIT $2
`

type ListHistoryMessagesParams struct {
	ConversationID int64
	Limit          int32
	CursorID       pgtype.Int8
}

func (q *Queries) ListHistoryMessages(ctx context.Context, arg ListHistoryMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listHistoryMessages, arg.ConversationID, arg.Limit, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MsgType,
			&i.Content,
			&i.CreatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, msg_type, content, created_at, is_deleted FROM messages
WHERE conversation_id = $1 
  AND is_deleted = false
  AND id < $2  -- 关键：基于 ID 过滤
ORDER BY id DESC -- 必须配合索引 (conversation_id, id)
LIMIT $3
`

type ListMessagesParams struct {
	ConversationID int64
	ID             int64
	Limit          int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MsgType,
			&i.Content,
			&i.CreatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySender = `-- name: ListMessagesBySender :many

SELECT id, conversation_id, sender_id, msg_type, content, created_at, is_deleted FROM messages
WHERE conversation_id = $1 and sender_id = $2 and is_deleted = false
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListMessagesBySenderParams struct {
	ConversationID int64
	SenderID       int64
	Limit          int32
	Offset         int32
}

// 只需要 Limit，不需要 Offset
func (q *Queries) ListMessagesBySender(ctx context.Context, arg ListMessagesBySenderParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBySender,
		arg.ConversationID,
		arg.SenderID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MsgType,
			&i.Content,
			&i.CreatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallMessage = `-- name: RecallMessage :one
UPDATE messages
SET is_deleted = true,
    content = '', -- 清空内容
    msg_type = 1  -- 转为文本类型（可选）
WHERE id = $1 
  AND sender_id = $2 -- 确保只能撤回自己的
  AND created_at > NOW() - INTERVAL '2 minutes' -- 时间限制
RETURNING id, conversation_id, sender_id, msg_type, content, created_at, is_deleted
`

type RecallMessageParams struct {
	ID       int64
	SenderID int64
}

func (q *Queries) RecallMessage(ctx context.Context, arg RecallMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, recallMessage, arg.ID, arg.SenderID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.MsgType,
		&i.Content,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}
