// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID int64
	// 1: private, 2: group
	Type      int16
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	OwnerID   pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ConversationMember struct {
	ID             int64
	ConversationID int64
	UserID         int64
	// 1:owner, 2:admin, 3:member. 私聊也默认为 3，避免 NULL
	Role     int16
	JoinedAt pgtype.Timestamptz
	// 0 表示未读任何消息
	LastReadMessageID pgtype.Int8
	LastActiveAt      pgtype.Timestamptz
}

type Friendship struct {
	ID       int64
	UserID   int64
	FriendID int64
	// pending: 待处理，accepted: 已接受，rejected: 已拒绝
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Blocked   pgtype.Bool
	// 好友备注名
	Remark pgtype.Text
}

type GroupAnnouncement struct {
	ID             int64
	ConversationID int64
	PublisherID    int64
	Content        string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type GroupMute struct {
	ID             int64
	ConversationID int64
	UserID         int64
	MutedUntil     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Message struct {
	ID             int64
	ConversationID int64
	SenderID       int64
	// 1:text, 2:image, 3:file, 4:voice
	MsgType   int16
	Content   string
	CreatedAt pgtype.Timestamptz
	IsDeleted pgtype.Bool
}

type MessageForward struct {
	ID                   int64
	OriginalMessageID    int64
	ForwardedBy          int64
	TargetConversationID int64
	ForwardedAt          pgtype.Timestamptz
}

type User struct {
	ID         int64
	Username   string
	PasswdHash string
	AvatarUrl  pgtype.Text
	// online, offline, busy
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserProfile struct {
	UserID    int64
	Nickname  pgtype.Text
	Signature pgtype.Text
	Gender    pgtype.Text
	Birthday  pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
