// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	BatchCreateMembers(ctx context.Context, arg BatchCreateMembersParams) ([]ConversationMember, error)
	CheckMemberExists(ctx context.Context, arg CheckMemberExistsParams) (bool, error)
	CountConversationMembers(ctx context.Context, conversationID int64) (int64, error)
	CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateConversationMember(ctx context.Context, arg CreateConversationMemberParams) (ConversationMember, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessage(ctx context.Context, id int64) (Message, error)
	GetConversation(ctx context.Context, id int64) (Conversation, error)
	GetConversationForUpdate(ctx context.Context, id int64) (Conversation, error)
	GetConversationMember(ctx context.Context, arg GetConversationMemberParams) (ConversationMember, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListConversationMembers(ctx context.Context, conversationID int64) ([]ConversationMember, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListMessagesBySender(ctx context.Context, arg ListMessagesBySenderParams) ([]Message, error)
	ListMyConversations(ctx context.Context, userID int64) ([]Conversation, error)
	RecallMessage(ctx context.Context, arg RecallMessageParams) (Message, error)
	RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error
	UpdataStatus(ctx context.Context, arg UpdataStatusParams) (User, error)
	UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (User, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdatePasswd(ctx context.Context, arg UpdatePasswdParams) (User, error)
	UpdateReadStatus(ctx context.Context, arg UpdateReadStatusParams) error
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
