CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "passwd_hash" varchar(255) NOT NULL,
  "avatar_url" varchar(255),
  "status" varchar(20) NOT NULL DEFAULT 'online',
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "conversations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" smallint NOT NULL,
  "name" varchar(100),
  "avatar_url" varchar(255),
  "owner_id" bigint,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "sender_id" bigint NOT NULL,
  "msg_type" smallint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "conversation_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "role" smallint NOT NULL DEFAULT 3,
  "joined_at" timestamptz DEFAULT (now()),
  "last_read_message_id" bigint DEFAULT 1,
  "last_active_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "conversations" ("owner_id");

CREATE INDEX ON "messages" ("conversation_id", "created_at");

CREATE INDEX ON "messages" ("conversation_id", "id");

CREATE INDEX ON "messages" ("sender_id", "created_at");

CREATE UNIQUE INDEX ON "conversation_members" ("conversation_id", "user_id");

CREATE INDEX ON "conversation_members" ("user_id");

COMMENT ON COLUMN "users"."status" IS 'online, offline, busy';

COMMENT ON COLUMN "conversations"."type" IS '1: private, 2: group';

COMMENT ON COLUMN "messages"."msg_type" IS '1:text, 2:image, 3:file, 4:voice';

COMMENT ON COLUMN "conversation_members"."role" IS '1:owner, 2:admin, 3:member. 私聊也默认为 3，避免 NULL';

COMMENT ON COLUMN "conversation_members"."last_read_message_id" IS '0 表示未读任何消息';

ALTER TABLE "conversations" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_members" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_members" ADD FOREIGN KEY ("last_read_message_id") REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- 好友关系表
CREATE TABLE "friendships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "friend_id" bigint NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),
  "blocked" boolean DEFAULT false,
  "remark" varchar(100),
  CONSTRAINT unique_friendship UNIQUE ("user_id", "friend_id")
);

-- 用户资料扩展表
CREATE TABLE "user_profiles" (
  "user_id" bigint PRIMARY KEY,
  "nickname" varchar(50),
  "signature" varchar(200),
  "gender" varchar(10),
  "birthday" date,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

-- 消息转发记录表
CREATE TABLE "message_forwards" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "original_message_id" bigint NOT NULL,
  "forwarded_by" bigint NOT NULL,
  "target_conversation_id" bigint NOT NULL,
  "forwarded_at" timestamptz DEFAULT (now())
);

-- 群公告表
CREATE TABLE "group_announcements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "publisher_id" bigint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "friendships" ("user_id");
CREATE INDEX ON "friendships" ("friend_id");
CREATE INDEX ON "friendships" ("status");
CREATE UNIQUE INDEX ON "friendships" ("user_id", "friend_id");

CREATE INDEX ON "message_forwards" ("original_message_id");
CREATE INDEX ON "message_forwards" ("forwarded_by");
CREATE INDEX ON "message_forwards" ("target_conversation_id");

CREATE INDEX ON "group_announcements" ("conversation_id");
CREATE INDEX ON "group_announcements" ("publisher_id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "friendships" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "message_forwards" ADD FOREIGN KEY ("original_message_id") REFERENCES "messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "message_forwards" ADD FOREIGN KEY ("forwarded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "message_forwards" ADD FOREIGN KEY ("target_conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "group_announcements" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "group_announcements" ADD FOREIGN KEY ("publisher_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

COMMENT ON COLUMN "friendships"."status" IS 'pending: 待处理，accepted: 已接受，rejected: 已拒绝';
COMMENT ON COLUMN "friendships"."remark" IS '好友备注名';

-- 群成员禁言表
CREATE TABLE "group_mutes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "muted_until" timestamptz NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "group_mutes" ("conversation_id");
CREATE INDEX ON "group_mutes" ("user_id");
CREATE UNIQUE INDEX ON "group_mutes" ("conversation_id", "user_id");

ALTER TABLE "group_mutes" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "group_mutes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
